In [1]:
import pandas as pd
import numpy as np

In [3]:
tac = pd.read_csv('./data/TAC_to_PNODE.csv')
sdge_pnode = pd.read_csv('./data/Node_Data/CAISO_SDGE_Node.csv')

In [4]:
tac

,TAC_AREA_ID,PNODE_ID,DESCRIPTION,COMMENTS,EFF_START_DT,EFF_END_DT,EFF_START_DT_GMT,EFF_END_DT_GMT
0,TAC_NORTH,OAKLND12_7_N101,TAC_NORTH,NaN,2021-01-01T00:00:00,2030-12-31T23:59:59,2021-01-01T08:00:00-00:00,2031-01-01T07:59:59-00:00
1,TAC_NORTH,PIT6U2_7_B1,TAC_NORTH,NaN,2022-05-26T00:00:00,2030-12-31T23:59:59,2022-05-26T07:00:00-00:00,2031-01-01T07:59:59-00:00
2,TAC_NORTH,CAPTJACK_5_N015,TAC_NORTH,NaN,2022-01-01T00:00:00,2030-12-31T23:59:59,2022-01-01T08:00:00-00:00,2031-01-01T07:59:59-00:00
3,TAC_NORTH,Q481_7_GN001,TAC_NORTH,NaN,2017-11-01T00:00:00,2030-12-31T23:59:59,2017-11-01T07:00:00-00:00,2031-01-01T07:59:59-00:00
4,TAC_BANC,ELK_GNODEESC,TAC_BANC,NaN,2022-01-01T00:00:00,2030-12-31T23:59:59,2022-01-01T08:00:00-00:00,2031-01-01T07:59:59-00:00
...,...,...,...,...,...,...,...,...
3866,TAC_BPAT,HRW_1_HOPKRIDG_PLANT-APND,TAC_BPAT,NaN,2022-05-03T00:00:00,2030-12-31T23:59:59,2022-05-03T07:00:00-00:00,2031-01-01T07:59:59-00:00
3867,TAC_ECNTR,SCNW_6_PDRP66-APND,TAC_ECNTR,NaN,2022-07-01T00:00:00,2030-12-31T23:59:59,2022-07-01T07:00:00-00:00,2031-01-01T07:59:59-00:00
3868,TAC_ECNTR,SCEC_1_PDRP187-APND,TAC_ECNTR,NaN,2022-07-01T00:00:00,2030-12-31T23:59:59,2022-07-01T07:00:00-00:00,2031-01-01T07:59:59-00:00
3869,TAC_NORTH,PGF1_2_PDRP108-APND,TAC_NORTH,NaN,2022-07-11T00:00:00,2030-12-31T23:59:59,2022-07-11T07:00:00-00:00,2031-01-01T07:59:59-00:00
3870,TAC_BPAT,UPRCOL_5_BASE_ORA-APND,TAC_BPAT,NaN,2022-05-03T00:00:00,2030-12-31T23:59:59,2022-05-03T07:00:00-00:00,2031-01-01T07:59:59-00:00

In [6]:
sdge_pnode

,AS_ID,RES_TYPE,RES_ID,PNODE_ID,BUS_ID,FNMVERSION,RELEASE_DATE,GROUP,Lat,Long,Unnamed: 10
0,AS_SP26,GEN,SYDRO_6_FCELL,SANYSDRO_6_N013,22740_SANYSDRO_69.0_GUM1,22M7_DB114,2022-07-28 0:00:00,4836,32.545077,-117.069661,NaN
1,AS_SP15,GEN,SYDRO_6_FCELL,SANYSDRO_6_N013,22740_SANYSDRO_69.0_GUM1,22M7_DB114,2022-07-28 0:00:00,4836,32.545077,-117.069661,NaN
2,AS_SP15,LOAD,SYDRO_6_LD32,SANYSDRO_6_N004,22740_SANYSDRO_69.0_LD32,22M7_DB114,2022-07-28 0:00:00,4838,32.562128,-117.026591,NaN
3,AS_SP26,LOAD,SYDRO_6_LD32,SANYSDRO_6_N004,22740_SANYSDRO_69.0_LD32,22M7_DB114,2022-07-28 0:00:00,4838,32.562128,-117.026591,NaN
4,AS_SP26,LOAD,SYDRO_6_LD31,SANYSDRO_6_N001,22740_SANYSDRO_69.0_LD31,22M7_DB114,2022-07-28 0:00:00,4837,32.562157,-117.026397,NaN
...,...,...,...,...,...,...,...,...,...,...,...
511,AS_SP26,LOAD,SNTABL_6_LD30,SANTYSBL_6_N001,22736_SANTYSBL_69.0_LD1,22M7_DB114,2022-07-28 0:00:00,4655,33.110721,-116.671113,NaN
512,AS_SP26,LOAD,WRNERS_6_LD1,WARNERS_6_N001,22884_WARNERS _69.0_LD1,22M7_DB114,2022-07-28 0:00:00,5340,33.247363,-116.675766,NaN
513,AS_SP15,LOAD,WRNERS_6_LD1,WARNERS_6_N001,22884_WARNERS _69.0_LD1,22M7_DB114,2022-07-28 0:00:00,5340,33.247363,-116.675766,NaN
514,AS_SP26,GEN,BREGGO_6_SOLAR,BORREGO_6_N009,22084_BORREGO _69.0_GU1,22M7_DB114,2022-07-28 0:00:00,397,33.291239,-116.353036,NaN
515,AS_SP15,GEN,BREGGO_6_SOLAR,BORREGO_6_N009,22084_BORREGO _69.0_GU1,22M7_DB114,2022-07-28 0:00:00,397,33.291239,-116.353036,NaN

In [14]:
joined_sdge = sdge_pnode[sdge_pnode['RES_TYPE']=='GEN'].join(tac.set_index('PNODE_ID'), on='PNODE_ID')

In [17]:
joined_sdge[joined_sdge['TAC_AREA_ID']=='TAC_SOUTH']

,AS_ID,RES_TYPE,RES_ID,PNODE_ID,BUS_ID,FNMVERSION,RELEASE_DATE,GROUP,Lat,Long,Unnamed: 10,TAC_AREA_ID,DESCRIPTION,COMMENTS,EFF_START_DT,EFF_END_DT,EFF_START_DT_GMT,EFF_END_DT_GMT
0,AS_SP26,GEN,SYDRO_6_FCELL,SANYSDRO_6_N013,22740_SANYSDRO_69.0_GUM1,22M7_DB114,2022-07-28 0:00:00,4836,32.545077,-117.069661,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2017-11-01T00:00:00,2030-12-31T23:59:59,2017-11-01T07:00:00-00:00,2031-01-01T07:59:59-00:00
1,AS_SP15,GEN,SYDRO_6_FCELL,SANYSDRO_6_N013,22740_SANYSDRO_69.0_GUM1,22M7_DB114,2022-07-28 0:00:00,4836,32.545077,-117.069661,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2017-11-01T00:00:00,2030-12-31T23:59:59,2017-11-01T07:00:00-00:00,2031-01-01T07:59:59-00:00
6,AS_SP15,GEN,BORDER_6_UNITA1,CPBORDER_7_B1,22149_CPBORDER_13.8_GU1,22M7_DB114,2022-07-28 0:00:00,371,32.566132,-116.944759,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2022-01-01T00:00:00,2030-12-31T23:59:59,2022-01-01T08:00:00-00:00,2031-01-01T07:59:59-00:00
7,AS_SP26,GEN,BORDER_6_UNITA1,CPBORDER_7_B1,22149_CPBORDER_13.8_GU1,22M7_DB114,2022-07-28 0:00:00,371,32.566132,-116.944759,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2022-01-01T00:00:00,2030-12-31T23:59:59,2022-01-01T08:00:00-00:00,2031-01-01T07:59:59-00:00
12,AS_SP26,GEN,LARKSP_6_UNIT 2,BDLRKSP2_7_B1,22075_BDLRKSP2_13.8_GU2,22M7_DB114,2022-07-28 0:00:00,2043,32.567450,-116.942317,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2022-07-20T00:00:00,2030-12-31T23:59:59,2022-07-20T07:00:00-00:00,2031-01-01T07:59:59-00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,AS_SP26,GEN,SONGS_7_UNIT 3,SONOFR3_7_B1,24130_S.ONOFR3_22.0_GU3,22M7_DB114,2022-07-28 0:00:00,4671,33.369248,-117.553319,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2017-11-01T00:00:00,2030-12-31T23:59:59,2017-11-01T07:00:00-00:00,2031-01-01T07:59:59-00:00
502,AS_SP15,GEN,CRSTWD_6_KUMYAY,KUMEYAAY_7_N001,22904_KUMEYAAY_34.5_GUKY,22M7_DB114,2022-07-28 0:00:00,863,32.699015,-116.353949,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2022-01-01T00:00:00,2030-12-31T23:59:59,2022-01-01T08:00:00-00:00,2031-01-01T07:59:59-00:00
503,AS_SP26,GEN,CRSTWD_6_KUMYAY,KUMEYAAY_7_N001,22904_KUMEYAAY_34.5_GUKY,22M7_DB114,2022-07-28 0:00:00,863,32.699015,-116.353949,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2022-01-01T00:00:00,2030-12-31T23:59:59,2022-01-01T08:00:00-00:00,2031-01-01T07:59:59-00:00
514,AS_SP26,GEN,BREGGO_6_SOLAR,BORREGO_6_N009,22084_BORREGO _69.0_GU1,22M7_DB114,2022-07-28 0:00:00,397,33.291239,-116.353036,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2022-02-09T00:00:00,2030-12-31T23:59:59,2022-02-09T08:00:00-00:00,2031-01-01T07:59:59-00:00
515,AS_SP15,GEN,BREGGO_6_SOLAR,BORREGO_6_N009,22084_BORREGO _69.0_GU1,22M7_DB114,2022-07-28 0:00:00,397,33.291239,-116.353036,NaN,TAC_SOUTH,TAC_SOUTH,NaN,2022-02-09T00:00:00,2030-12-31T23:59:59,2022-02-09T08:00:00-00:00,2031-01-01T07:59:59-00:00

In [18]:
joined_sdge.to_csv('./data/Gen_Node_Data/sdge_gen_node_with_tac.csv')